### PR TITLE
Add metricAggregator to bin

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Review by rom1504 — CHANGES_REQUESTED** [review]
Can you use it in the action ?

**Comment by u9g** [comment]
yeah, this was going to be used for minecraft-data when its merged, and maybe merged into here to replace a manual .js file in the workflows folder

**Comment by rom1504** [comment]
I think it would be good to do the manual.js change in this PR to avoid code duplication

**Comment by u9g** [comment]
> I think it would be good to do the manual.js change in this PR to avoid code duplication

thats in a different repo: https://github.com/PrismarineJS/minecraft-packets/pull/13

**Comment by rom1504** [comment]
Oh ok, can you add this to readme / doc ?

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
