### PR TITLE
add new workflow for prs to seperate

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by u9g** [comment]
ready for review :)

**Review by rom1504 — CHANGES_REQUESTED** [review]
I think it's useful if the test run on normal commits too

**Comment by u9g** [comment]
> I think it's useful if the test run on normal commits too

ok, added it back, but only for master branch, should be good to go now

**Review by rom1504 — CHANGES_REQUESTED** [review]
ci.yml still runs on PR here

**Comment by u9g** [comment]
> ci.yml still runs on PR here

doesn't matter, I added this: https://github.com/PrismarineJS/prismarine-packet-dumper/blob/32337000bf495e3b6e4b8fe74bad1b0fe28a8515/.github/workflows/ci.yml#L30

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
